import "./globals.css";

import localFont from 'next/font/local'

// Font files can be colocated inside of `pages`
const monoska = localFont({ src: '../public/fonts/monoska/Monoska.ttf' })

export const metadata = {
  title: "Daniel Fisseha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monoska.className}>{children}</body>
    </html>
  );
}
